"""added avatar to user

Revision ID: 3b368e2d12e2
Revises: 896a4e5457ee
Create Date: 2022-10-23 15:14:32.907613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b368e2d12e2'
down_revision = '896a4e5457ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint(None, 'posts', ['id'])
    op.add_column('users', sa.Column(
        'avatar', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('users', sa.Column(
        'created_at', sa.TIMESTAMP(), nullable=False))
    # op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'users', ['avatar'])
    op.drop_column('users', 'registration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registration',
                  postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    # op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'avatar')
    # op.drop_constraint(None, 'posts', type_='unique')
    # ### end Alembic commands ###
