"""change name column

Revision ID: 896a4e5457ee
Revises: b838190dc20f
Create Date: 2022-10-13 16:09:04.472266

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '896a4e5457ee'
down_revision = 'b838190dc20f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'posts', ['id'])
    op.add_column('subscriptions', sa.Column(
        'created_at', sa.TIMESTAMP(), nullable=False))
    op.drop_column('subscriptions', 'sub_created_at')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('subscriptions', sa.Column('sub_created_at',
                  postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('subscriptions', 'created_at')
    op.drop_constraint(None, 'posts', type_='unique')
    # ### end Alembic commands ###
